version: "3.7"
services:
  # node 1
  centos7:
    build:
      context: ./nodes/centos7
      dockerfile: Dockerfile
    image: ansible-centos7
    container_name: ansible-centos7
    hostname: centos7
  # node 2
  ubuntu20:
    build:
      context: ./nodes/ubuntu20
      dockerfile: Dockerfile
    image: ansible-ubuntu20
    container_name: ansible-ubuntu20
    hostname: ubuntu20
    working_dir: /home/work_user
  # ansible実行環境
  myansible:
    build:
      context: .
      dockerfile: Dockerfile
    image: myansible
    container_name: myansible
    hostname: myansible
    tty: true
    volumes:
      - ./playbooks:/myansible
    working_dir: /myansible
